### ISSUE TITLE
[feat] 채팅 api 구현

### ISSUE THREAD

**Issue by jimmy0524** [billbill-project/bill-chat-server#6]
## 📌 To-do

채팅 api 구현

## ✅ 구현 내용

- [x] api 응답통일 및 예외처리
- [x] 이전 채팅 기록 불러오기 api
- [x] 채팅방 생성 웹훅
 
## ⏰ 예상 기간

11월 24일 ~ 11월 30일
